### ISSUE TITLE
Fossil Collection Not Showing Up

### ISSUE THREAD

**Issue by MadSciSlack** [XxRexRaptorxX/Collectibles#2]
Hey, cool mod! Are the fossils not working?  They don't show up in JEI or other searches where the other collections do.

**Comment by XxRexRaptorxX** [comment]
Can't find any error. Whats your MC & mod version?

**Comment by MadSciSlack** [comment]
MC 1.19.2, Mod version 1.2.3a

**Comment by XxRexRaptorxX** [comment]
Fossils are added in later versions (MC 1.19.3 and higher)

**Comment by MadSciSlack** [comment]
Okay, thanks for clarifying.  If you happen to get around to updating the 1.19.2 with the additional content, I for one would be most appreciative.  I know backporting features probably isn't high priority.
